server:
  port: 9000
spring :
  jpa :
    hibernate :
      ddl-auto : validate
    properties :
      hibernate :
        show_sql: true
        format_sql : true
  session:
    store-type: jdbc
  profiles:
    include: real-db
  config:
    use-legacy-processing: true
logging:
  level:
    org.hiberbate.SQL: debug
    org.hibernate.type: trace
