server:
  port: 9000
spring :
  datasource:
    url: jdbc:h2:~/joomak;
    username : sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa :
    hibernate :
      ddl-auto : create
    properties :
      hibernate :
        show_sql: true
        format_sql : true

logging:
  level:
    org.hiberbate.SQL: debug
    org.hibernate.type: trace